name: snake

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
   - cron: "0 23 * * *"

jobs:
  wakatime:
    runs-on: ubuntu-latest
    steps:
    - name: snake
      uses: lowlighter/metrics@latest
      with:
        filename: 27-5-22.svg
        token: NOT_NEEDED
        base: ""
        plugin_wakatime: yes
        plugin_wakatime_user: basussatoto
        plugin_wakatime_sections: Watch My Contribution Graph Get Eaten By the snake
        plugin_wakatime_token: ${{ secrets.SNAKE_TOKEN }}
